### ISSUE TITLE
Exception in Android when trying to connect to a device

### ISSUE THREAD

**Issue by joaowd** [pycampers/flutter-rx-ble#3]
This is the full log I get after scanning devices and trying to connect to one:

```
D/PluginScaffold(12964): invoke { channel: com.pycampers.rx_ble, method: requestAccess(), args: null }
I/zygote  (12964): Do partial code cache collection, code=19KB, data=30KB
I/zygote  (12964): After code cache collection, code=19KB, data=30KB
I/zygote  (12964): Increasing code cache capacity to 128KB
D/PluginScaffold(12964): onListen { channel: com.pycampers.rx_ble/scan, args: {scanMode=1, deviceName=null, deviceId=null} }
D/BluetoothAdapter(12964): isLeEnabled(): ON
D/BluetoothLeScanner(12964): onScannerRegistered() - status=0 scannerId=7 mScannerId=0
D/PluginScaffold(12964): invoke { channel: com.pycampers.rx_ble, method: stopScan(), args: null }
D/BluetoothAdapter(12964): isLeEnabled(): ON
D/PluginScaffold(12964): piping exception to flutter (java.lang.RuntimeException)
D/PluginScaffold(12964): piping exception to flutter (java.lang.RuntimeException)
D/PluginScaffold(12964): ignoring exception: java.lang.IllegalStateException: Reply already submitted. See https://github.com/flutter/flutter/issues/29092 for details.
D/PluginScaffold(12964): onCancel { channel: com.pycampers.rx_ble/scan, args: null }
D/PluginScaffold(12964): onListen { channel: com.pycampers.rx_ble/scan, args: {scanMode=1, deviceName=null, deviceId=30:AE:A4:9B:08:16} }
D/BluetoothAdapter(12964): isLeEnabled(): ON
D/PluginScaffold(12964): onCancel { channel: com.pycampers.rx_ble/scan, args: {scanMode=1, deviceName=null, deviceId=30:AE:A4:9B:08:16} }
D/BluetoothLeScanner(12964): onScannerRegistered() - status=0 scannerId=7 mScannerId=0
D/PluginScaffold(12964): onListen { channel: com.pycampers.rx_ble/connect, args: {waitForDevice=true, deviceId=30:AE:A4:9B:08:16} }
D/BluetoothAdapter(12964): isLeEnabled(): ON
D/PluginScaffold(12964): piping exception to flutter (java.lang.RuntimeException)
W/System.err(12964): io.reactivex.exceptions.OnErrorNotImplementedException: The exception was not handled due to missing onError handler in the subscribe() method call. Further reading: https://github.com/ReactiveX/RxJava/wiki/Error-Handling | java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: pool-1-thread-1
W/System.err(12964): 	at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:704)
W/System.err(12964): 	at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:701)
W/System.err(12964): 	at io.reactivex.internal.observers.LambdaObserver.onError(LambdaObserver.java:77)
W/System.err(12964): 	at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:67)
W/System.err(12964): 	at io.reactivex.internal.operators.observable.ObservableDoFinally$DoFinallyObserver.onNext(ObservableDoFinally.java:80)
W/System.err(12964): 	at io.reactivex.internal.operators.observable.ObservableSkip$SkipObserver.onNext(ObservableSkip.java:56)
W/System.err(12964): 	at io.reactivex.internal.operators.observable.ObservableDistinctUntilChanged$DistinctUntilChangedObserver.onNext(ObservableDistinctUntilChanged.java:85)
W/System.err(12964): 	at com.jakewharton.rxrelay2.BehaviorRelay$BehaviorDisposable.test(BehaviorRelay.java:364)
W/System.err(12964): 	at com.jakewharton.rxrelay2.BehaviorRelay$BehaviorDisposable.emitNext(BehaviorRelay.java:358)
W/System.err(12964): 	at com.jakewharton.rxrelay2.BehaviorRelay.accept(BehaviorRelay.java:135)
W/System.err(12964): 	at com.polidea.rxandroidble2.internal.DeviceModule$1.onConnectionStateChange(DeviceModule.java:68)
W/System.err(12964): 	at com.polidea.rxandroidble2.internal.operations.ConnectOperation$4.subscribe(ConnectOperation.java:148)
W/System.err(12964): 	at io.reactivex.internal.operators.single.SingleCreate.subscribeActual(SingleCreate.java:39)
W/System.err(12964): 	at io.reactivex.Single.subscribe(Single.java:3603)
W/System.err(12964): 	at io.reactivex.internal.operators.single.SingleDoFinally.subscribeActual(SingleDoFinally.java:44)
W/System.err(12964): 	at io.reactivex.Single.subscribe(Single.java:3603)
W/System.err(12964): 	at io.reactivex.Single.subscribeWith(Single.java:3650)
W/System.err(12964): 	at com.polidea.rxandroidble2.internal.operations.ConnectOperation.protectedRun(ConnectOperation.java:80)
W/System.err(12964): 	at com.polidea.rxandroidble2.internal.QueueOperation$1.subscribe(QueueOperation.java:41)
W/System.err(12964): 	at io.reactivex.internal.operators.observable.ObservableCreate.subscribeActual(ObservableCreate.java:40)
W/System.err(12964): 	at io.reactivex.Observable.subscribe(Observable.java:12268)
W/System.err(12964): 	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
W/System.err(12964): 	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
W/System.err(12964): 	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:26)
W/System.err(12964): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
W/System.err(12964): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
W/System.err(12964): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
W/System.err(12964): 	at java.lang.Thread.run(Thread.java:764)
W/System.err(12964): Caused by: java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: pool-1-thread-1
W/System.err(12964): 	at io.flutter.embedding.engine.FlutterJNI.ensureRunningOnMainThread(FlutterJNI.java:605)
W/System.err(12964): 	at io.flutter.embedding.engine.FlutterJNI.dispatchPlatformMessage(FlutterJNI.java:515)
W/System.err(12964): 	at io.flutter.embedding.engine.dart.DartMessenger.send(DartMessenger.java:76)
W/System.err(12964): 	at io.flutter.embedding.engine.dart.DartExecutor.send(DartExecutor.java:151)
W/System.err(12964): 	at io.flutter.view.FlutterNativeView.send(FlutterNativeView.java:144)
W/System.err(12964): 	at io.flutter.plugin.common.EventChannel$IncomingStreamRequestHandler$EventSinkImplementation.success(EventChannel.java:226)
W/System.err(12964): 	at com.pycampers.plugin_scaffold.PluginScaffoldPluginKt$trySend$4.invoke(PluginScaffoldPlugin.kt:122)
W/System.err(12964): 	at com.pycampers.plugin_scaffold.PluginScaffoldPluginKt$trySend$4.invoke(Unknown Source:0)
W/System.err(12964): 	at com.pycampers.plugin_scaffold.PluginScaffoldPluginKt$trySend$1.invoke(PluginScaffoldPlugin.kt:117)
W/System.err(12964): 	at com.pycampers.plugin_scaffold.PluginScaffoldPluginKt$trySend$1.invoke(Unknown Source:0)
W/System.err(12964): 	at com.pycampers.plugin_scaffold.PluginScaffoldPluginKt.ignoreIllegalState(PluginScaffoldPlugin.kt:49)
W/System.err(12964): 	at com.pycampers.plugin_scaffold.PluginScaffoldPluginKt.trySend(PluginScaffoldPlugin.kt:116)
W/System.err(12964): 	at com.pycampers.plugin_scaffold.PluginScaffoldPluginKt.trySend(PluginScaffoldPlugin.kt:122)
W/System.err(12964): 	at com.pycampers.rx_ble.ConnectMethods$connect$5.accept(ConnectMethods.kt:49)
W/System.err(12964): 	at com.pycampers.rx_ble.ConnectMethods$connect$5.accept(ConnectMethods.kt:22)
W/System.err(12964): 	at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63)
W/System.err(12964): 	... 24 more
D/View    (12964): [Warning] assignParent to null: this = DecorView@eb061ad[MainActivity]
D/WindowClient(12964): Remove from mViews: DecorView@eb061ad[MainActivity], this = android.view.WindowManagerGlobal@7aa7ce2
```

**Comment by devxpy** [comment]
Would it be possible to provide a minimum reproducible example?

Does this instantly crash the app, or does it only prevent the expected functionality?

**Comment by joaowd** [comment]
Hey there,

Yeah everything is working now, I just tried in android for the first time after updating flutter/ios/android and everything works now :)

Just one note, I downloaded the project instead of using via pub.dev
